### ISSUE TITLE
Sugestão de temas

### ISSUE THREAD

**Issue by raphaelfabeni** [raphaelfabeni/css-sp#22]
Fala pessoal! Tudo bem?
Além de enviar [idéias de talks](https://meetupcss.typeform.com/to/I4Gp5L), pensamos em abrir um espaço (beta) para sugestão de temas a serem discutidos/apresentados no Meetup CSS.

Sem medo, envie sua idéia e caso queira apresentar algo mas não tenha idéia do assunto, talvez aqui possa ser a sua fonte de inspiração para achar um tema. 

Abaixo, algumas das sugestões que a galera já deu. :metal: 
- [ ] Usos bizarros do transform.
- [ ] Jogos feitos com CSS
- [ ] Abordagem de unidades medidas diferentes (px, em, %)
- [x] Diferentes formas de abordar um mesmo problema (_dojo, pair_)
- [x] Estruturação do projeto (divisão de pastas e arquivos)
- [ ] Soluções de contorno nada ortodoxas

**Comment by designernatan** [comment]
Usos bizarros do transform.

**Comment by cassiocardoso** [comment]
Jogos feitos somente em CSS.

**Comment by khigashi** [comment]
Não participei dos anteriores então é só uma ideia que não sei se já tiveram, mas acho legal abordar algo que estamos estudando muito aqui e implantando em projetos que é a abordagem de unidades de medidas diferentes aceitas pelo W3C como "**em, %**" no lugar do **px** para suportar a entrada de diferentes dispositivos/tecnologias/tamanhos de telas.

**Comment by emersonjds** [comment]
As palestras estao sendo fantasticas mas há uma coisa que gostaria de abordar nao sei se é viavel mas seria interessante uma forma de interagir com a galera em forma de dojo ou pair programming, de maneira que o palestrante colocasse desafios para o pessoal conseguir resolver, englobando não só quem ja frequenta e trabalha com as ferramentas diariamente mas também aqueles que estao começando, falo isso por que levo bastante amigo pra ir porem eles saem cheio de duvidas, e depois tentam resolver aquele problema e não conseguem, querendo abordar determinado assunto que foi dado na palestra. Acho interessante este tipo de abordagem por que voce instiga a pessoa a ir aprender e tambem mostrar a ideia de como ela resolveria determinada situação, todos temos maneiras diferentes de pensar e em cima destas maneiras abordadas ocorrer uma discussão do por que do x e não do y na resolução daquele problema, levando em consideração os melhores padroes de desenvolvimento web. Só uma sugestão acho que seria bacana :)

**Comment by renatogalvones** [comment]
Ainda não consegui participar de uma edição(trampo em Alphaville 😭  ) mas seria bacana(se já não for a 238ª vez que falam disso) falar sobre estruturação de projetos. Metodologias de divisão dos css e quem sabe do projeto como um todo mesmo.

Pergunta: Os meetups são gravados de alguma forma? Nem que fosse somente o aúdio acho que seria bacana. Talvez até liberar isso como se fosse um podcast, assim o alcance não ficaria limitado somente a quem vai no evento. 😉

**Comment by raphaelfabeni** [comment]
@renatogalvones respondendo a sua pergunta: não são gravados não. Já tentamos fazer live pelo Hangouts mas tivemos alguns problemas com internet e ouvimos muita reclamação por causa disso. É algo que podemos pensar, mas por enquanto, não temos a intenção de gravar.

@emersonjds respondendo a sua pergunta: sempre falei isso nas apresentações iniciais, talvez de uma forma diferente que era trazer um problema e todos resolverem juntos. É uma idéia legal. Podemos tentar abordar com algo nos próximos.

**Comment by renatogalvones** [comment]
@raphaelfabeni Pensem com carinho na questão de gravar o aúdio então. 😄 

É algo que não demanda tanta energia, dá pra fazer até pelo celular e depois disponibilizar a gravação em alguma plataforma free.

Com o tempo vcs poderiam pensar em formato de cast e talz, mas acho que seria um começo bacana.

**Comment by raphaelfabeni** [comment]
@renatogalvones pode deixar! Mas demanda uma certa energia sim, pois caso o áudio não fique legal, abriremos espaço para reclamações, e como nossos encontros se baseiam em talks e em algumas edições com discussões, não sei até que ponto o áudio seria útil. De qualquer forma valeu pela idéia.

**Comment by elvisdetona** [comment]
Diferentes formas de abordar um mesmo problema (dojo, pair). Pair com css seria sensacional... pq por mais que muitas pessoas usem a mesma metodologia, cada um escreve de um jeito.

**Comment by talitapagani** [comment]
Jogos feitos com CSS
Diferentes formas de abordar um mesmo problema (dojo, pair)

**Comment by rogeriorioli** [comment]
Estruturação do projeto (divisão de pastas e arquivos)

**Comment by designernatan** [comment]
Soluções de contorno nada ortodoxas

**Comment by lnfnunes** [comment]
* Abordagem de unidades medidas diferentes (px, em, %)
* Diferentes formas de abordar um mesmo problema (dojo, pair)
* Estruturação do projeto (divisão de pastas e arquivos)

**Comment by cassiocardoso** [comment]
[Element Queries](http://elementqueries.stfi.re/)

**Comment by raphaelfabeni** [comment]
Esse *uso bizarros do transform* seria demais..

**Comment by raphaelfabeni** [comment]
2017 chegou! Aqueles que tem vontade de apresentar algo, mas estão sem idéia, no primeiro comentário dessa issue, temos algumas sugestões. Vale lembrar que todos que palestrarem ganham uma assessoria completa da Caelum. 😄

**Comment by emersonjds** [comment]
Utilização de pre processadores de forma correta, organização de pastas, *PAIR PROGRAMMING" , uma coisa legal seria um desafio de layout  que alguém poderia trazer para ser resolvido, assim os participantes se dividiriam em pares para resolver os desafios, depois os códigos seriam apresentados o que geraria uma discussão do por que a utilização daquela estrutura de pasta, nomenclaturas e tal, olhando e comparando se aprende demais, pondo a mão na massa tem a troca de experiencias do cara que é mais sênior sei la com o cara que começou agora, e melhora o networking da comunidade já que uma hora todos trabalharão com todos.

**Comment by raphaelfabeni** [comment]
Fala @emersonjds ! Tudo bem? Legal! Valeu! A maioria do que você sugeriu nós já fizemos em algumas edições: organizações de pastas e estrutura já foi tema em umas 2 ou 3 edições; já fizemos uma edição de dojo com a divisão da galera em 2 times; já fizemos também um desafio de layout mas a idéia era escrever a estrutura de CSS no papel. Podemos repetir alguns desses.

**Comment by emersonjds** [comment]
A do papel deve ter sido massa hahahaha, imagina lembrar de todas as propriedades hahahaha, acho que responsividade utilizando Sass seria uma boa , ainda tenho dificuldade na declaração de funções e condicionais dentro do Sass, de qualquer forma qualquer que for feito vou marcar presença :D

Grande abraço

Att,

Emerson Silva

--
Att,

Emerson Silva

sexta-feira, 13 janeiro 2017, 10:07AM -02:00 de Raphael Fabeni notifications@github.com<mailto:notifications@github.com>:


Fala @emersonjds<https://github.com/emersonjds> ! Tudo bem? Legal! Valeu! A maioria do que você sugeriu nós já fizemos em algumas edições: organizações de pastas e estrutura já foi tema em umas 2 ou 3 edições; já fizemos uma edição de dojo com a divisão da galera em 2 times; já fizemos também um desafio de layout mas a idéia era escrever a estrutura de CSS no papel. Podemos repetir alguns desses.

**Comment by raphaelfabeni** [comment]
@emersonjds foi bem legal!

vamos fechar essa issue e a reabrimos em breve, quando retornarmos.
